#!/bin/bash

# activate hk_libs environment
eval "$(conda shell.bash hook)"
conda activate hk_libs

# cd to the directory of this script
cd "$(dirname "$0")"

# build distribution
rm -rf dist/*
python setup.py bdist_wheel

# upload to pypi
twine upload dist/*